[project]
name = "translater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-openai>=0.3.31",
    "pymupdf>=1.26.4",
    "pypdf2>=3.0.1",
]
